
name: This is the first workflow
on: push
        
jobs:
   hello:
    runs-on: ubuntu-latest

    steps:
        - name: checkout
          uses: action/checkout@v3
        
        - name: Job run
          uses: setup-python@v2
        - run: python person.py
    

 