
name: This is the first workflow
on: push
        
jobs:
   hello:
    runs-on: ubuntu-latest

    steps:
        - name: checkout
          uses: actions/checkout@v3
        
        - name: Job run
          uses: actions/setup-python@v2
          
        - name: Execting job
          run: python person.py
    

 