
name: This is the first workflow
on: push
        
jobs:
   hello:
    runs-on: ubuntu-latest

    steps:
        - name: checkout
          uses: actions/checkout@v4
        
        - name: Job run
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Execting to extract the report
          run: |
               echo "executing the script"
               python person.py
    

 